### ISSUE TITLE
JSON Parse Bug Sighting

### ISSUE THREAD

**Issue by RobertESinger** [sentry07/netlinx-libJSON#3]
Hi -

We last exchanged notes about a year and a half ago.  I've been using your parser extensively.  I think I may have tripped over a bug:

Error message:

[JSON] Validator returned the following error: ERROR at position 1: Start of array only valid in value.

URL sent is:

https://api.openweathermap.org/geo/1.0/reverse?lat=33.3089&lon=-111.7597&limit=10&appid=275191df4cf9dd0e08f3c410021a6033

JSON data returned is:

[{"name":"Gilbert","local_names":{"en":"Gilbert","ru":"Гилберт","uk":"Гілберт"},"lat":33.3527632,"lon":-111.7890373,"country":"US","state":"Arizona"}]

Can you please look into this?

Let me know if you need more information.

Thanks - Bob Singer

**Comment by sentry07** [comment]
Glad to hear you're getting a lot of use out of it. Any feedback other than this?

The JSON_ParseObject function expects to have a base object of dictionary type with at least one key:value pair. The fact that this API endpoint straight up returns an array of dictionaries is outside the norm, to say the least.

I don't think this is a bug, per se. It's "functioning as intended" because you're running JSON_ParseObject (which calls the validator), and the data you're trying to parse is technically not a JSON Object, it's an array, so it would error out in the JSON_ParseValidObject function anyway. JSON_ParseArray would have no problem with this data and would return a single element array. 

I would check the first character of the return and call the appropriate function (JSON_ParseObject or JSON_ParseArray) based on that. If you feel this isn't a satisfactory answer, I'm open to ideas on how to handle it internal to the JSON library.

**Comment by RobertESinger** [comment]
Hi -

Strictly speaking, I agree with your technical assessment.  We can close this as "working as intended".

By the time your response arrived I was already well on my way to implementing what would become your suggestion, and now have it working.  The next work-around test I'll try will be to to add curly braces at the beginning and end of the JSON response and feed it to your parser.

As far as any other feedback, I have only one comment:  When chewing through large JSON responses, it will bury the Netlinx processor.  In my application, the processor becomes immune to interaction for the duration of the parse and traversal for 20-25 seconds.  Not good when the user is trying to watch TV.  NI-700 & 900s don't have enough horsepower as secondary processors in this application.  Seems like NI-X100 and larger will work.

So, I added another processor to the system, whose sole purpose is to grind through JSON data and ship the resulting parsed information back to the primary processor, which is also taxing, but not as bad.  I've had to do this with other real-time applications, so it's not too bad.

I poked around in the parser to try to process smaller JSON chunks, then give up the CPU, and return later to resume parsing.  Everything I tried blew a crater in the call stack and destroyed the data.  The parser and traversal use recursion (as well they should) and any disruption to the call stack causes big problems.  The design of the Netlinx environment isn't robust enough for sophisticated programming.  The static, non-reentrant event thread processing the JSON response must execute to completion.  I frequently feel like the Professor on Gilligan's Island, trying to make radar sets and washing machines from coconut shells and palm fronds.

The only other way to pick-up speed would be to revisit the parser and traversal routines to make them more efficient, which could be a large undertaking.  I've written enough parsers in my day...  So, I'll just put it out there as a suggestion to mull over, not a formal request.

With a viable work-around I soldier on.

Thanks - Bob

**Comment by RobertESinger** [comment]
Not a bug - working as intended.

**Comment by RobertESinger** [comment]
Comment:  In reviewing the JSON syntax standard, I don't see anything that requires the topmost thing in a JSON string must be an object between curly braces.  It looks like it can be any JSON value, including an object, array, number, string, and the three literal name tokens true, false and null.

https://www.ecma-international.org/wp-content/uploads/ECMA-404_2nd_edition_december_2017.pdf

What do you think?

Bob

**Comment by RobertESinger** [comment]
Here's an online JSON parser that seems to accept what the standard document says:

https://jsonformatter.org/json-parser

**Comment by sentry07** [comment]
I released this on Github to welcome any and all updates. If it can be optimized, feel free to do so. This is as optimized as I could come up with, which cut down processing time to under a second on an NI-3100 on some large JSON data I'm parsing on one of my jobs. However, yes, it does require a full sized NI-x100 or NX processor to not become a process hog. I think the only way you could make it better would be to write a Duet module.

As far as the JSON syntax standard, you're looking at what a value of a key:value pair can be: string, number, object, array, and the literal tokens. The JSON_ParseObject function is designed to parse literally a JSON Object, which is a dictionary layout. If you try to pass an array into JSON_ParseObject, it will error because it's not a valid Object. The array that you're receiving from the API is valid JSON _data_, and you can put it in a JSON validator and it will tell you it's valid, but it's not a valid JSON Object.

What I _think_ you're looking for is a function like JSON_Parse, which would look at the data and depending on what type of data it finds, passes the data onto the proper function, JSON_ParseObject or JSON_ParseArray. And that would be great to do, except we're working in Netlinx and we don't have dynamic data types. So you would have to account for both types of returns with your byRef parameters, and do something like

dataType = JSON_Parse(data, jObjectReturn, jArrayReturn, arrayRecordCount)

With dataType being 'object' or 'array', and then fork your logic based on that to read the data from jObjectReturn or jArrayReturn.
